### ISSUE TITLE
How to get the correct idx for mutation inference

### ISSUE THREAD

**Issue by AthenACHY** [pagnani/ArDCA.jl#26]
Hi,

I am trying to use the package to do mutational influence and I use the alignment file (.a2m) generated from EVcoupling as the input of arDCA. From what I understand arnet reordered the columns in the running process and I can use idxperm to locate the correct site of my mutations. 
I also found that arnet would drop some columns from the alignment too and is there a way to find out what columns were dropped and which sites from the original alignments are preserved in the idxperm so that I can map the mutations annotations onto the xori for mutation influence?

thanks in advance for your help!

**Comment by pagnani** [comment]
Indeed, as explained [here](https://github.com/pagnani/ArDCA.jl/blob/master/julia-notebook/tutorial.ipynb) (see 3. Predicting mutational effects), 
```
D,idxgap=dms_single_site(arnet,arvar,target_sequence)
```
returns `D` a  `q x L` matrix containing the mutational effects, and `idxgap` the indices of gap in the reference sequence.

**Comment by pagnani** [comment]
closing
